### ISSUE TITLE
Adding to the project

### ISSUE THREAD

**Issue by bryanjjohnson** [Smartrak/mapbox-gl-js-typescript#1]
I added some of the missing parts to the typings file. I haven't been able to make a pull request to add to the project. Is the project open for that, or would you rather I send the changes to you some other way?

**Comment by danzel** [comment]
Hi Bryan. Not sure why you can't make a PR, maybe you didn't fork the repo?

There have been some discussions over here about this repository:
https://github.com/mapbox/mapbox-gl-js/issues/2440

We're planning to move to dobrud's repository:
https://github.com/dobrud/typed-mapbox-gl

This repo has a few features his doesn't, but we'll add those on. (This week sometime)
