### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by ghost** [Smartrak/mapbox-gl-js-typescript#6]
I am using mapbox-gl in my typescript project.
I followed your instructions and get error

TypeScript error: typings/modules/mapbox-gl/index.d.ts(224,61): Error TS1110: Type expected.

Can you please help me with this issue?

**Comment by danzel** [comment]
I'd compare what you are doing to the example project
https://github.com/danzel/mapboxgl-webpack-example

And post what the line that is generating the error looks like. 224 is blank in the repository.

Thanks.

**Comment by alexsparrow** [comment]
I'm hitting the same error here. The line number difference is due to typings adding some boilerplate at the top of the file. 

The line in question for me looks like:

```
setMaxBounds(bounds: LngLatBounds | Array<Array<number>> |null| undefined): this;
```

**Comment by danzel** [comment]
Thanks, fixed!
